# 
# kind delete cluster --name rwmlseries-34fa
#
# docker network rm rwmlseries-34fa-network
# docker network create --subnet 172.100.0.0/16 rwml-34fa-network
# KIND_EXPERIMENTAL_DOCKER_NETWORK=rwmlseries-34fa-network kind create cluster --config ./kind/kind-with-portmapping.yaml
#
# Show status:
#
# kubectl get nodes --show-labels
# kubectl cluster-info --context kind-rwmlseries-34fa
#
---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: rwmlseries-34fa
networking:
  podSubnet: "10.100.0.0/16"
nodes:
  - role: control-plane
    image: kindest/node:v1.31.4
    kubeadmConfigPatches:
    - |
      kind: InitConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "ingress-ready=true"

    extraPortMappings:
    - containerPort: 81
      hostPort: 81
      protocol: TCP

    - containerPort: 444
      hostPort: 444
      protocol: TCP

    - containerPort: 31093
      hostPort: 9093
      listenAddress: "127.0.0.1"
      protocol: TCP
# Expose Kafka broker to localhost:31234
    - containerPort: 31237
      hostPort: 31237
      listenAddress: "127.0.0.1"
      protocol: TCP

    - containerPort: 31238
      hostPort: 31238
      listenAddress: "127.0.0.1"

    - containerPort: 31239
      hostPort: 31239
      listenAddress: "127.0.0.1"
